### ISSUE TITLE
Not cloning content of repo, but rather the content of .git

### ISSUE THREAD

**Issue by BenJeau** [JaciBrunning/git_backup#2]
This option [bare](https://docs.rs/git2/latest/git2/build/struct.RepoBuilder.html#method.bare) is set to `true` which only clones the `.git` folder at the root of the folder. It would be as simple as removing this line

https://github.com/JaciBrunning/git_backup/blob/master/src/git.rs#L39

I can make a quick PR if you want me to

**Comment by JaciBrunning** [comment]
Hi,

Yes, this is intentional. The README gives a little insight as to why:

"Cloned repositories are bare repos. You can clone from these repositories
by adding the file path as a remote, or push them directly to a remote in
order to restore the backup. The repository is bare as to avoid unecessary
extra data usage by checking out the git tree, but rather storing the
packed objects."

The other reason is that bare repository avoids a bunch of pull/checkout
headaches and edge cases when pulling from force-pushed remotes, or where
the history is not straight-forward.

Just removing the `bare: true` option unfortunately reintroduces these
issues and would require a lot of extra logic to suit these edge cases
(some of which is a little obtuse in the git2 rs library). The good news is
that the .git folder contains the entire repository changeset, so your code
and content is still there, it just has to be checked out with clone or by
adding the backup as a remote.

You can clone from the local directory with `git clone <file>` if you'd
like to verify or load the backup.

Hope this helps,
Jaci

**Comment by BenJeau** [comment]
Thank you, it makes sense!
